### PR TITLE
fixed display version of removed nginx, make code some more readable

### PR DESCRIPTION
**Pull request by encorer**
Found error in display version of removed nginx. With awk, I was not able to achieve the required accuracy, so I found another way, based on grep with regexp match. This method cut by match, instead of awk's choosing a match field, that can change its place.

### CODE REVIEW

**Comment by hex-344505** [comment]
Good job, but
./script.sh: line 48: sudo: command not found
./script.sh: line 50: lsb_release: command not found
./script.sh: line 51: sudo: command not found
./script.sh: line 53: curl: command not found
./script.sh: line 53: sudo: command not found
./script.sh: line 55: sudo: command not found
./script.sh: line 57: sudo: command not found

So i should install it manualy

nginx: [warn] conflicting server name "localhost" on 0.0.0.0:80, ignored
Can we avoid this warning?

**Comment by encorer** [comment]
What linux version are you running? How do you run this script? I wrote and tested on default installation of Ubuntu, and script must be running with sudo.

**Comment by encorer** [comment]
nginx: [warn] conflicting server name "localhost" on 0.0.0.0:80, ignored - because I add to include - /sites-enabled too.

**Comment by hex-344505** [comment]
> What linux version are you running? How do you run this script? I wrote and tested on default installation of Ubuntu, and script must be running with sudo.

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by encorer** [comment]
`sudo ./script.sh` 
and can I please get the full output along with the launch line? e.g. my output:

```
vlad@vlad-ubuntu:~$ sudo ./script.sh 
Nginx not found, do you want to install? [Y,n]
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет ca-certificates самой новой версии (20180409).
Уже установлен пакет lsb-release самой новой версии (9.20170808ubuntu1).
Уже установлен пакет curl самой новой версии (7.58.0-2ubuntu3.8).
Уже установлен пакет gnupg2 самой новой версии (2.2.4-1ubuntu1.2).
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 26 пакетов не обновлено.
deb http://nginx.org/packages/ubuntu bionic nginx
OK
Сущ:1 http://ua.archive.ubuntu.com/ubuntu bionic InRelease
Сущ:2 http://ua.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Сущ:3 http://nginx.org/packages/ubuntu bionic InRelease                        
Сущ:4 http://ua.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Сущ:5 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Чтение списков пакетов… Готово                                                 
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Может быть обновлено 26 пакетов. Запустите «apt list --upgradable» для их показа.
N: Пропускается получение настроенного файла «nginx/binary-i386/Packages», так как репозиторий «http://nginx.org/packages/ubuntu bionic InRelease» не поддерживает архитектуру «i386»
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Выбрана версия «1.14.2-1~bionic» (nginx:stable [amd64]) для «nginx»
Следующие НОВЫЕ пакеты будут установлены:
  nginx
Обновлено 0 пакетов, установлено 1 новых пакетов, для удаления отмечено 0 пакетов, и 26 пакетов не обновлено.
Необходимо скачать 836 kB архивов.
После данной операции объём занятого дискового пространства возрастёт на 2 933 kB.
Пол:1 http://nginx.org/packages/ubuntu bionic/nginx amd64 nginx amd64 1.14.2-1~bionic [836 kB]
Получено 836 kB за 1с (1 051 kB/s)
Выбор ранее не выбранного пакета nginx.
(Чтение базы данных … на данный момент установлено 168265 файлов и каталогов.)
Подготовка к распаковке …/nginx_1.14.2-1~bionic_amd64.deb …
----------------------------------------------------------------------

Thanks for using nginx!

Please find the official documentation for nginx here:
* http://nginx.org/en/docs/

Please subscribe to nginx-announce mailing list to get
the most important news about nginx:
* http://nginx.org/en/support.html

Commercial subscriptions for nginx are available on:
* http://nginx.com/products/

----------------------------------------------------------------------
Распаковывается nginx (1.14.2-1~bionic) …
Настраивается пакет nginx (1.14.2-1~bionic) …
Обрабатываются триггеры для man-db (2.8.3-2ubuntu0.1) …
Обрабатываются триггеры для ureadahead (0.100.0-21) …
Обрабатываются триггеры для systemd (237-3ubuntu10.31) …
Dirs present: /etc/nginx/
mkdir: невозможно создать каталог «/etc/nginx/sites-enabled»: Файл существует
mkdir: невозможно создать каталог «/etc/nginx/sites-available»: Файл существует
"sites-enabled" found
sites-enabled not found
default.conf in /etc/nginx/sites_available/
Link default.conf in /etc/nginx/sites-enabled/


Nginx not running. Start? [Y/n]
Start the Nginx
Started
Welcome to nginx!
Nginx main process have a PID: 7783
Nginx worker PIDs: 1 
```

**Comment by hex-344505** [comment]
root@ca179f92531c:/# ./script.sh 
Nginx not found, do you want to install? [Y,n]
./script.sh: line 48: sudo: command not found
./script.sh: line 51: sudo: command not found
./script.sh: line 50: lsb_release: command not found
./script.sh: line 53: sudo: command not found
./script.sh: line 53: curl: command not found
./script.sh: line 55: sudo: command not found
./script.sh: line 57: sudo: command not found
Could not find nginx directory
cat: /nginx.conf: No such file or directory
cat: /etc/nginx/nginx.conf: No such file or directory
cat: /etc/nginx/nginx.conf: No such file or directory
./script.sh: line 76: /etc/nginx/output: No such file or directory
./script.sh: line 84: /etc/nginx/nginx.conf: No such file or directory
cat: /etc/nginx/nginx.conf: No such file or directory
cat: /etc/nginx/nginx.conf: No such file or directory
sites-enabled not found
No file default.conf in /sites-available/
No link default.conf in /sites-enabled/
./script.sh: line 135: sudo: command not found
./script.sh: line 136: sudo: command not found


Nginx not running. Start? [Y/n]
Start the Nginx
./script.sh: line 154: sudo: command not found
./script.sh: line 135: sudo: command not found
./script.sh: line 136: sudo: command not found
Nginx not started. Repair with you hands

**Comment by encorer** [comment]
Are you kidding me? You know perfectly well why this is happening.

**Comment by hex-344505** [comment]
> Are you kidding me? You know perfectly well why this is happening.

yes i know, and i said that sudo and lsb_release should be installed manually before running script. your script almost perfect except this case and nginx warning.
it can be fixed just adding 
apt-get update && apt-get install -y sudo curl lsb_release

**Comment by encorer** [comment]
Then I need to consider that no one package of used in my script is not present, and they are also not in the repository, so I need to download the sources and compile. But with the compiler, too, things may not be so smooth. Therefore, I focus on the system on which I run the script, and by default, these packages present are in ubuntu.

**Comment by hex-344505** [comment]
скрипт хороший но требует зависимостей

**Pull request merged**
